### ISSUE TITLE
display goat density 

### ISSUE THREAD

**Issue by samccone** [joelhawksley/helios#4]
:chart_with_upwards_trend: :goat:

**Comment by samccone** [comment]
http://www.washingtonpost.com/blogs/wonkblog/wp/2015/01/12/map-literally-every-goat-in-the-united-states/

**Comment by markalfred** [comment]
:+1: this is a showstopper for us

**Comment by codeurge** [comment]
+1 no business like goat business.

**Comment by samccone** [comment]
:(
